export enum ErrorCode {
  IllegalTransition = 'ILLEGAL_TRANSITION',
  VersionConflict = 'VERSION_CONFLICT',
  SeparationOfDuties = 'SEPARATION_OF_DUTIES',
  MfaRequired = 'MFA_REQUIRED',
  MfaInvalid = 'MFA_INVALID',
  MfaReuse = 'MFA_REUSE',
  InvalidCredentials = 'INVALID_CREDENTIALS',
  AccountLocked = 'ACCOUNT_LOCKED',
  InactiveAccount = 'INACTIVE_ACCOUNT',
  RefreshTokenReuse = 'REFRESH_TOKEN_REUSE',
  ResourceNotFound = 'RESOURCE_NOT_FOUND',
  ValidationError = 'VALIDATION_ERROR',
  Conflict = 'CONFLICT',
  Unauthorized = 'UNAUTHORIZED',
  Forbidden = 'FORBIDDEN',
  NotFound = 'NOT_FOUND',
  RequestFailed = 'REQUEST_FAILED',
  InternalError = 'INTERNAL_ERROR',
}
