export enum ApplicationAction {
  CreateDraft = 'create_draft',
  UpdateDraft = 'update_draft',
  UploadDocument = 'upload_document',
  Submit = 'submit',
  Withdraw = 'withdraw',
  Claim = 'claim',
  Assign = 'assign',
  RequestInfo = 'request_info',
  Resubmit = 'resubmit',
  RecommendApproval = 'recommend_approval',
  RecommendRejection = 'recommend_rejection',
  Approve = 'approve',
  Reject = 'reject',
}
