export enum ApplicationAction {
  CreateDraft = 'create_draft',
  UpdateDraft = 'update_draft',
  UploadDocument = 'upload_document',
  UpsertCapitalDeclaration = 'upsert_capital_declaration',
  CreateShareholder = 'create_shareholder',
  UpdateShareholder = 'update_shareholder',
  DeleteShareholder = 'delete_shareholder',
  MarkShareholderFitAndProper = 'mark_shareholder_fit_and_proper',
  CreateSeniorManager = 'create_senior_manager',
  UpdateSeniorManager = 'update_senior_manager',
  DeleteSeniorManager = 'delete_senior_manager',
  SubmitFeeProof = 'submit_fee_proof',
  IssueInformationLetter = 'issue_information_letter',
  SlaBreached = 'sla_breached',
  Submit = 'submit',
  Withdraw = 'withdraw',
  Claim = 'claim',
  Assign = 'assign',
  RequestInfo = 'request_info',
  Resubmit = 'resubmit',
  RecommendApproval = 'recommend_approval',
  RecommendRejection = 'recommend_rejection',
  Approve = 'approve',
  Reject = 'reject',
  Defer = 'defer',
}
