export enum DocumentSlot {
  ApplicantInformationSheet = 'APPLICANT_INFORMATION_SHEET',
  ShareholderInformationSheet = 'SHAREHOLDER_INFORMATION_SHEET',
  PersonalDeclaration = 'PERSONAL_DECLARATION',
  CreditReport = 'CREDIT_REPORT',
  CapitalStructure = 'CAPITAL_STRUCTURE',
  BusinessPlan = 'BUSINESS_PLAN',
  IncorporationCertificate = 'INCORPORATION_CERTIFICATE',
  BoardResolution = 'BOARD_RESOLUTION',
  ApplicationFeeProof = 'APPLICATION_FEE_PROOF',
  FinancialStatements = 'FINANCIAL_STATEMENTS',
  FitAndProperForm = 'FIT_AND_PROPER_FORM',
  HomeSupervisorNoObjection = 'HOME_SUPERVISOR_NO_OBJECTION',
  HomeSupervisorConsolidatedSupervision = 'HOME_SUPERVISOR_CONSOLIDATED_SUPERVISION',
  HomeSupervisorMouConfirmation = 'HOME_SUPERVISOR_MOU_CONFIRMATION',
  Other = 'OTHER',
}

export const DOCUMENT_SLOT_LABELS: Record<DocumentSlot, string> = {
  [DocumentSlot.ApplicantInformationSheet]: 'Applicant information sheet',
  [DocumentSlot.ShareholderInformationSheet]: 'Shareholder information sheet',
  [DocumentSlot.PersonalDeclaration]: 'Personal declaration',
  [DocumentSlot.CreditReport]: 'Credit report',
  [DocumentSlot.CapitalStructure]: 'Capital structure',
  [DocumentSlot.BusinessPlan]: 'Business Plan',
  [DocumentSlot.IncorporationCertificate]: 'Incorporation Certificate',
  [DocumentSlot.BoardResolution]: 'Board resolution',
  [DocumentSlot.ApplicationFeeProof]: 'Application fee proof',
  [DocumentSlot.FinancialStatements]: 'Financial Statements',
  [DocumentSlot.FitAndProperForm]: 'Fit & Proper Form',
  [DocumentSlot.HomeSupervisorNoObjection]: 'Home supervisor no-objection',
  [DocumentSlot.HomeSupervisorConsolidatedSupervision]: 'Consolidated supervision confirmation',
  [DocumentSlot.HomeSupervisorMouConfirmation]: 'Home supervisor MoU confirmation',
  [DocumentSlot.Other]: 'Other Document',
};
